# Generated by Django 4.2.6 on 2024-02-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_checkoutaddress_item_order_orderitem_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("A", "Apple"),
                    ("HP", "HP"),
                    ("acer", "Acer"),
                    ("MS", "Microsoft"),
                    ("R", "Razer"),
                    ("Huaw", "Huawei"),
                    ("Del", "Dell"),
                    ("Ln", "Lenovo"),
                    ("AS", "Asus"),
                    ("Thin", "ThinkPad"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[("N", "New"), ("BS", "Best deal")], max_length=10
            ),
        ),
    ]
